# Prometheus Configuration
# Tells Prometheus what to monitor

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitor our Flask app
  - job_name: 'cloudops-app'
    static_configs:
      - targets: ['localhost:5000']
    metrics_path: '/api/metrics'

  # Monitor Docker containers (if running)
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
    metrics_path: '/metrics'
